# Generated by Django 6.1.1 on 2026-09-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.ForeignKey(blank=True, help_text='LGA the user belongs to (required for officers/inspectors).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='lga.lga'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
