# Generated by Django 6.1.1 on 2026-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nida_number',
            field=models.CharField(blank=True, db_index=True, help_text='National Identification Number (NIDA), 20 digits, verified via integrations app.', max_length=20),
        ),
    ]
