# Generated by Django 6.1.1 on 2026-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('state', models.CharField(choices=[('START', 'Main menu'), ('APPLY_LGA', 'Apply: pick council'), ('APPLY_LICENCE', 'Apply: pick licence'), ('APPLY_BUSINESS', 'Apply: pick business'), ('APPLY_PURPOSE', 'Apply: purpose / confirm'), ('STATUS_SELECT', 'Status: pick application'), ('PAY_SELECT_INVOICE', 'Pay: pick invoice'), ('PAY_AMOUNT', 'Pay: amount'), ('PAY_PHONE', 'Pay: phone'), ('EXITED', 'Ended')], default='START', max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
