# Generated by Django 6.1.1 on 2026-09-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tin_number', models.CharField(blank=True, help_text='TRA TIN, verified via integrations app.', max_length=20)),
                ('brela_registration_number', models.CharField(blank=True, max_length=30)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Set once BRELA/TRA verification passes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TIN_CERTIFICATE', 'TIN Certificate'), ('BRELA_CERTIFICATE', 'BRELA Registration Certificate'), ('LEASE_AGREEMENT', 'Lease Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='business_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='businesses.business')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('plot_number', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='businesses.business')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_locations', to='lga.lga')),
            ],
            options={
                'ordering': ['-is_primary', 'ward'],
            },
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_business_name_per_owner'),
        ),
    ]
