# Generated by Django 6.1.1 on 2026-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_tinapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='nida_number',
            field=models.CharField(blank=True, help_text="Owner NIDA captured with the registration (snapshot of the owner's NIDA).", max_length=20),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='kind',
            field=models.CharField(choices=[('TIN_CERTIFICATE', 'TIN Certificate'), ('BRELA_CERTIFICATE', 'BRELA Registration Certificate'), ('STREET_ID_LETTER', 'Street Identification Letter'), ('LEASE_AGREEMENT', 'Lease Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
