# Generated by Django 6.1.1 on 2026-09-22 22:38

import core_docs.validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_nida_number_alter_businessdocument_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinapplication',
            name='nida_number',
            field=models.CharField(blank=True, help_text='National ID number of the taxpayer, as printed on the NIDA card.', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='file',
            field=models.FileField(upload_to='business_documents/%Y/%m/', validators=[core_docs.validation.validate_pdf_document]),
        ),
        migrations.CreateModel(
            name='TINApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NIDA_COPY', 'Copy of National ID (NIDA)'), ('PASSPORT_PHOTO', 'Passport-size photo'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='tin_applications/%Y/%m/', validators=[core_docs.validation.validate_pdf_document])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tin_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='businesses.tinapplication')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
