# Generated by Django 6.1.1 on 2026-10-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_tinapplication_nida_number_and_more'),
        ('lga', '0009_alter_businessactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Kind of business — the council activity taxonomy shown at registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='lga.businessactivity'),
        ),
        migrations.AlterField(
            model_name='business',
            name='sector',
            field=models.CharField(blank=True, help_text='Free-text fallback; prefer activity.', max_length=100),
        ),
    ]
