# Generated by Django 6.1.1 on 2026-10-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_activity_alter_business_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('tra_valid', models.BooleanField(help_text='Null means TRA was unreachable.', null=True)),
                ('tra_reason', models.CharField(blank=True, max_length=255)),
                ('brela_registered', models.BooleanField(help_text='Null means BRELA was unreachable.', null=True)),
                ('brela_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'verification attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
