# Generated by Django 6.1.1 on 2026-09-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=15)),
                ('purpose', models.CharField(choices=[('SUBMISSION', 'Application submitted'), ('CORRECTION', 'Returned for correction'), ('APPROVAL', 'Application approved'), ('CONTROL_NUMBER', 'Control number issued'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('ISSUANCE', 'Licence issued'), ('REJECTION', 'Application rejected'), ('RENEWAL', 'Renewal update'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('backend', models.CharField(blank=True, help_text='SMS backend used to send.', max_length=100)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='applications.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS log entry',
                'verbose_name_plural': 'SMS log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
