# Generated by Django 6.1.1 on 2026-09-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('BRELA', 'BRELA'), ('TRA', 'TRA'), ('GePG', 'Government Electronic Payment Gateway'), ('USSD', 'USSD Gateway')], max_length=10)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound request'), ('INBOUND', 'Inbound (mock response)')], max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
