# Generated by Django 6.1.1 on 2026-09-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('lga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INSPECTION_SCHEDULED', 'Inspection scheduled'), ('INSPECTED', 'Inspected'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('ISSUED', 'Issued'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('purpose_statement', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='businesses.business')),
                ('licence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lga.licencetype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='businesses.businesslocation')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_application', 'Can review applications'), ('inspect_application', 'Can conduct inspections'), ('approve_application', 'Can approve applications')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_documents', to='lga.requirement')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('conducted_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('passed', models.BooleanField(blank=True, help_text='Null until the inspection is conducted.', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='applications.application')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INSPECTION_SCHEDULED', 'Inspection scheduled'), ('INSPECTED', 'Inspected'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('ISSUED', 'Issued'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('REJECTED', 'Rejected')], max_length=30)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INSPECTION_SCHEDULED', 'Inspection scheduled'), ('INSPECTED', 'Inspected'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('ISSUED', 'Issued'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('REJECTED', 'Rejected')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'status histories',
                'ordering': ['changed_at'],
            },
        ),
    ]
