# Generated by Django 6.1.1 on 2026-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
