# Generated by Django 6.1.1 on 2026-09-22 22:38

import core_docs.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='application_documents/%Y/%m/', validators=[core_docs.validation.validate_pdf_document]),
        ),
    ]
