# Generated by Django 6.1.1 on 2026-09-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationdocument_file'),
        ('lga', '0007_lga_tier_licencetype_bylaw_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_signature_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inspection',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='inspection_photos/%Y/%m/')),
                ('client_capture_time', models.DateTimeField()),
                ('server_receipt_time', models.DateTimeField(auto_now_add=True)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('exif_data', models.JSONField(blank=True, default=dict)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='lga.inspectionchecklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='applications.inspection')),
            ],
            options={
                'ordering': ['server_receipt_time'],
            },
        ),
    ]
