# Generated by Django 6.1.1 on 2026-09-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('validity_months', models.PositiveIntegerField(default=12)),
                ('requires_inspection', models.BooleanField(default=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_types', to='lga.lga')),
            ],
            options={
                'ordering': ['lga__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_review', models.BooleanField(default=True)),
                ('can_inspect', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('licence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lga.licencetype')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('DOCUMENT', 'Document'), ('INSPECTION', 'Inspection'), ('CLEARANCE', 'External clearance')], default='DOCUMENT', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('licence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='lga.licencetype')),
            ],
            options={
                'ordering': ['licence_type', 'order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='licencetype',
            constraint=models.UniqueConstraint(fields=('lga', 'code'), name='unique_licence_type_code_per_lga'),
        ),
        migrations.AddConstraint(
            model_name='officerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('officer', 'licence_type'), name='unique_active_assignment'),
        ),
    ]
