# Generated by Django 6.1.1 on 2026-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencetype',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('DRIVING', 'Driving'), ('GENERAL', 'General')], db_index=True, default='BUSINESS', max_length=20),
        ),
    ]
