# Generated by Django 6.1.1 on 2026-09-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0002_licencetype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lga',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='licencetype',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
