# Generated by Django 6.1.1 on 2026-09-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0003_alter_lga_code_alter_lga_name_alter_licencetype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
