# Generated by Django 6.1.1 on 2026-09-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0004_alter_lga_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencetype',
            name='code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
