# Generated by Django 6.1.1 on 2026-09-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0005_alter_licencetype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='lga.lga')),
            ],
            options={
                'ordering': ['lga__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('lga', 'name'), name='unique_ward_per_lga')],
            },
        ),
    ]
