# Generated by Django 6.1.1 on 2026-09-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0006_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='tier',
            field=models.CharField(choices=[('CITY', 'City Council'), ('MUNICIPAL', 'Municipal Council'), ('TOWN', 'Town Council'), ('DISTRICT', 'District Council')], default='DISTRICT', max_length=20),
        ),
        migrations.AddField(
            model_name='licencetype',
            name='bylaw_reference',
            field=models.URLField(blank=True, help_text='Link to enabling bylaw document'),
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('licence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='lga.licencetype')),
            ],
            options={
                'ordering': ['licence_type', 'order', 'name'],
            },
        ),
    ]
