# Generated by Django 6.1.1 on 2026-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0008_businessactivity_licencetype_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessactivity',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='businessactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Short hint shown under the activity name (examples of businesses).'),
        ),
        migrations.AlterField(
            model_name='businessactivity',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional UI icon identifier.', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessactivity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on selection screens.'),
        ),
    ]
