# Generated by Django 6.1.1 on 2026-09-20 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (control number not yet requested)'), ('WAITING_PAYMENT', 'Waiting for payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired (control number no longer valid)')], db_index=True, default='PENDING', max_length=20)),
                ('gepg_bill_id', models.CharField(blank=True, max_length=50)),
                ('gepg_approval', models.CharField(blank=True, help_text='GePG payment reference / receipt number.', max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('control_number_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='applications.application')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile money'), ('BANK', 'Bank'), ('AGENT', 'Agent'), ('CASH', 'Cash (government office)')], default='MOBILE_MONEY', max_length=20)),
                ('payer_name', models.CharField(blank=True, max_length=150)),
                ('payer_phone', models.CharField(blank=True, max_length=15)),
                ('reference', models.CharField(blank=True, help_text='External transaction reference (e.g. M-Pesa code).', max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.invoice')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
