# Generated by Django 6.1.1 on 2026-09-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='GePG receipt; empty until reconciliation succeeds.', max_length=30, unique=True),
        ),
    ]
