# Generated by Django 6.1.1 on 2026-09-20 14:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('lga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('RENEWAL_PENDING', 'Renewal pending'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField()),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='licence', to='applications.application')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences', to='lga.lga')),
                ('licence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences', to='lga.licencetype')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved (payment pending)'), ('PAID', 'Paid'), ('ISSUED', 'Renewed licence issued'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_valid_until', models.DateField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='licences.licence')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licence_renewals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
